### ISSUE TITLE
Cannot send headers to client

### ISSUE THREAD

**Issue by upayanmazumder** [kspcommunity/kspcommunity.com#48]
This occurs on successful signup both on localhost and production

```
::ffff:XXX.XX.XX.XX- - [07/Jun/2024:03:57:24 +0000] "POST /api/signup HTTP/1.1" 200 1675 "-" "node"
Error: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:703:11)
    at ServerResponse.header (/home/container/node_modules/express/lib/response.js:795:10)
    at ServerResponse.send (/home/container/node_modules/express/lib/response.js:175:12)
    at ServerResponse.json (/home/container/node_modules/express/lib/response.js:279:15)
    at ServerResponse.send (/home/container/node_modules/express/lib/response.js:163:21)
    at /home/container/api/routes/signup.js:23:29
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by upayanmazumder** [comment]
nvm i fixed it. had wrong version on server
